format = """
$username\
$hostname\
[ $directory [](#64748B)](bg:#64748B)[$git_branch$git_status]()[[](fg:#263238 bg:#4e5166)$cmd_duration$character[](fg:#4e5166)](bg:#4e5166) """

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bg:#64748B"

[git_branch]
symbol = " "
format = " [\\[$symbol$branch\\]]($style) "
style = "purple"

[git_status]
style = "red"

[cmd_duration]
format = " [$duration]($style)"
style = "fg:#94a3b8 bg:#4e5166"

[character]
success_symbol = ""
error_symbol = "[ !](bold fg:red bg:#4e5166)"

[nodejs]
disabled = true

[ruby]
disabled = true

[gcloud]
disabled = true