format = """
$username\
$hostname\
[ $directory [](#64748B)](bg:#64748B) [$git_branch$git_status](bold)"""

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold bg:#64748B"

[git_branch]
symbol = " "
format = "[\\[$symbol$branch\\]]($style) "


[nodejs]
disabled = true

[ruby]
disabled = true

[gcloud]
disabled = true