format = """
[ $directory [](#7284A8)](bg:#7284A8) [$git_branch$git_status](bold)"""

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold bg:#7284A8"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[nodejs]
disabled = true

[ruby]
disabled = true

[gcloud]
disabled = true