format = """
$username\
$hostname\
[ $directory [](#64748B)](bg:#64748B)[$git_branch$git_status](bold)[[](fg:#263238 bg:#44475a)$cmd_duration$character[](fg:#44475a)](bg:#44475a) """

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold bg:#64748B"

[git_branch]
symbol = " "
format = " [\\[$symbol$branch\\]]($style) "

[cmd_duration]
format = " [$duration]($style)"
style = "fg:#94a3b8 bg:#44475a"

[character]
success_symbol = ""
error_symbol = "[ !](bold fg:red bg:#44475a)"

[nodejs]
disabled = true

[ruby]
disabled = true

[gcloud]
disabled = true