format = """
$username\
$hostname\
[ $directory [](#64748B)](bg:#64748B)[$git_branch$git_status](bold)[[](fg:#263238 bg:#94A3B8)$cmd_duration[](#94A3B8)](bg:#94A3B8) """

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold bg:#64748B"

[git_branch]
symbol = " "
format = " [\\[$symbol$branch\\]]($style) "

[cmd_duration]
format = " [$duration]($style) "
style = "fg:#263238 bg:#94A3B8"

[nodejs]
disabled = true

[ruby]
disabled = true

[gcloud]
disabled = true